### PR TITLE
Mcs new

### PR DESCRIPTION
**Pull request by axelvonkamp**
The real changes are actually in the two submodules efmtool_link and optlang_enumerator.

### CODE REVIEW

**Comment by sthiele** [comment]
The commit history looks pretty scrambled. Should I clean this up or do you want to do it?

**Comment by axelvonkamp** [comment]
> The commit history looks pretty scrambled. Should I clean this up or do you want to do it?

I wasn't aware that it is possible to modify the commit history. Perhaps you can do it before I mess it up even further ;-)

**Comment by sthiele** [comment]
Ok, can you double check if this is Ok https://github.com/klamt-lab/cnapy/compare/st/mcs_new?expand=1
If yes create a new  PR from branch and I suggest that we squash the commits

**Comment by axelvonkamp** [comment]
OK, I have made the pull request for the other branch and am closing this one.

**Pull request closed without merging**
