### PR TITLE
St/mcs new

### PR DESCRIPTION
**Pull request by axelvonkamp**

### CODE REVIEW

**Comment by axelvonkamp** [comment]
What is still needed is a mechanism to get the packages from github during cnapy installation.

**Comment by sthiele** [comment]
I propose we create a conda package. I can help with that and create a PR in efmtool_link.

**Comment by axelvonkamp** [comment]
> I propose we create a conda package. I can help with that and create a PR in efmtool_link.

Could a PyPI regstration be sufficient? conda has so much overhead...

**Comment by sthiele** [comment]
You can do both. I would be pretty happy to get rid of PyPI packages for cnapy. 
> conda has so much overhead...
Creation and upload of the packages can be automated as for PyPI

**Comment by axelvonkamp** [comment]
> I propose we create a conda package. I can help with that and create a PR in efmtool_link.

Thanks, please create the PR so that I can get an impression what is required to make it a conda package.

**Pull request merged**
